name: tests

on: [push, pull_request]

env: 
  go_version: '1.22'
  golangci_version: 'v1.59.1'
jobs:
  in-memory:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}

      - name: check out code
        uses: actions/checkout@v3

      - name: run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.golangci_version }}
          args: --config=.golangci.yml --issues-exit-code=0

      - name: build 
        run: make build 
      
      - name: tests
        run: make test

      - name: code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage.html
          path: ./build/
