name: tests

on: [push, pull_request]

jobs:
  in-memory:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.22

      - name: check out code
        uses: actions/checkout@v3

      - name: linters
        run: make lint

      - name: build 
        run: make build 
      
      - name: tests
        run: make test

      - name: code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage.out
          path: ./build/code-coverage.html
